[project]
name = "mo"
version = "0.1.0"
description = "Project to run marimo pages"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.13.5",
    "matplotlib>=3.10.3",
    "polars>=1.29.0",
    "pyarrow>=20.0.0",
]
